org: nagaraj
app: api-pdf-service
service: express-pdf-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    
      

